#!/usr/bin/env python3
"""
Generate FBR API Key
Quick script to generate and save an FBR API key
"""

import requests
import sys
from pathlib import Path

def main():
    print("🔑 Generating FBR API key...")
    
    try:
        response = requests.post('https://fbrapi.com/generate_api_key')
        response.raise_for_status()
        
        data = response.json()
        api_key = data.get('api_key')
        
        if not api_key:
            print("❌ No API key in response")
            print(f"Response: {data}")
            return
        
        print(f"✅ Generated API key: {api_key}")
        print()
        
        # Save to .env file
        env_file = Path(__file__).parent.parent / ".env"
        
        # Check if key already exists
        if env_file.exists():
            with open(env_file, 'r') as f:
                content = f.read()
                if 'FBREF_API_KEY' in content:
                    print("⚠️  Warning: FBREF_API_KEY already exists in .env")
                    response = input("Overwrite? (y/N): ")
                    if response.lower() != 'y':
                        print("Skipping .env update")
                        print(f"\nTo use this key, run:")
                        print(f"export FBREF_API_KEY='{api_key}'")
                        return
        
        # Write to .env
        with open(env_file, 'a') as f:
            f.write(f"\n# FBR API Key (generated by generate_fbr_api_key.py)\n")
            f.write(f"FBREF_API_KEY={api_key}\n")
        
        print(f"💾 Saved to {env_file}")
        print()
        print("🚀 You can now run:")
        print("   python scripts/ingest_fbref_data.py")
        
    except requests.exceptions.RequestException as e:
        print(f"❌ Error making request: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()